### ISSUE TITLE
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)

### ISSUE THREAD

**Issue by HPark0517** [tud-amr/social_vrnn#1]
I am reporting a problem with DataHandler module import:

/social_vrnn/src$ ./train.sh
Using Python 3
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from src.data_utils import DataHandler as dh
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)
Using Python 3
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from src.data_utils import DataHandler as dh
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)
Using Python 3
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from src.data_utils import DataHandler as dh
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)
Using Python 3
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from src.data_utils import DataHandler as dh
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)
Using Python 3
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from src.data_utils import DataHandler as dh
ImportError: cannot import name 'DataHandler' from 'src.data_utils' (unknown location)

Thank you

**Comment by bbrito** [comment]
I'll check it today. Sorry for the delay. I just saw your msg.

**Comment by PFery4** [comment]
The ```src/data_utils``` folder does not contain any file named ```DataHandler.py```

Line 20 of the ```train.py``` file might be an artifact remaining from a previous build where there was a ```DataHandler``` file, maybe? The line can be commented out and the code should work just fine.

Anyway, I am not sure if this will be useful, since I'm answering an 1.5 years old issue, but HTH.

**Comment by bbrito** [comment]
This class is not necessary. The DataHandlerLSTM is the one it should be used. I have removed the dependency
