### ISSUE TITLE
broken link to download the trained_models.zip file

### ISSUE THREAD

**Issue by PFery4** [tud-amr/social_vrnn#4]
reproducing the error:

try to execute the ```./dowload_data.sh``` script

output: receive ERROR 503 (Service Unavailable) upon sending the https request for reaching the ```trained_models.zip``` file

I suppose this is due to a broken link for this specific file. Downloading the ```data.zip``` file works just fine.

**Comment by bbrito** [comment]
Sorry for the late reply but that folder was deleted from my repository because I am no longer a TU Delft student. Unfortunately, I did not manage to recover the trained models. I would recommend to use the code to train one from scratch.
