### ISSUE TITLE
KL annealing coefficient inconsistent with publication?

### ISSUE THREAD

**Issue by PFery4** [tud-amr/social_vrnn#7]
https://github.com/tud-amr/social_vrnn/blob/707cadaac2f42cd869608cb3927ea25a4a60a1e0/src/models/SocialVRNN.py#L234

Here we have the definition of the KL annealing coefficient, which does not correspond to the definition mentioned in the publication.
The publication mentions:
![image](https://user-images.githubusercontent.com/61045673/195039145-3805a399-9499-4023-b4c2-80609be4dc77.png)

"We used a KL annealing coefficient λ = tanh( (step - 10^4) /10^3 ), with step as the training step."

Which of the two is correct?

**Comment by bbrito** [comment]
hum good question. I am sorry but I do not have the original code with me anymore but I am pretty confident the the paper values should be the ones to use.
