### ISSUE TITLE
Time parameters used during the experiments produced in the article?

### ISSUE THREAD

**Issue by PFery4** [tud-amr/social_vrnn#8]
I would like to know what value of the `truncated_backprop_length` parameter was used for producing the results displayed in the publication.

The `train.sh` script hints at the value being either 1 or 12. Was there a fixed value chosen for all experiments across the 5 datasets from UCY/ETH?

On this topic, I would just like to know for sure, the observation time T_O mentioned in the article is 8, however the few trainings shown as examples in the `train.sh` script indicate either 0 or 7. Was the value of `prev_horizon` chosen as 8 in your experiments?

Finally, could you tell me what is the reason behind the implementation of both truncated backpropagation through time `truncated_backprop_length` and the choice of a set observation time `prev_horizon`? I understand that they both operate in different manners in the code. But as implemented in this way currently, the input feature vectors for the past trajectories are essentially shifted versions of the velocity signal of the query agent, as such:
batch_vel.shape = [batch_size, truncated_backprop_length, input_state_dim * (prev_horizon + 1)]

Let:
```
truncated_backprop_length = 3
prev_horizon = 4
```

Then:
```
batch_vel[0] = 
[[vx_-2, vy_-2, vx_-3, vy_-3, vx_-4, vy_-4, vx_-5, vy_-5, vx_-6, vy_-6],
 [vx_-1, vy_-1, vx_-2, vy_-2, vx_-3, vy_-3, vx_-4, vy_-4, vx_-5, vy_-5],
 [vx_0, vy_0, vx_-1, vy_-1, vx_-2, vy_-2, vx_-3, vy_-3, vx_-4, vy_-4]]
```
This results in an input feature vector containing duplicate values of the velocity signal across time truncations within the batch (ie, in the second dimension of the batch).

**Comment by bbrito** [comment]
For the results presented in the article I have used prev_horizon as 8. This is the standard used across all prediciton papers. For the truncated_back_propagation I have tried different parameters. If the dataset has large enough trajectories the value that works best is to set truncated_backprop_length to be the same as the prediciton horizon. If your dataset only contains small trajectories you should use a lower value for the truncated_backprop_length

**Comment by bbrito** [comment]
the inspiration to use truncated back propagation comes from [here](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=VpgOLqQAAAAJ&citation_for_view=VpgOLqQAAAAJ:ufrVoPGSRksC)
