### ISSUE TITLE
Error in Support.rotate_batch_to_local_frame() function

### ISSUE THREAD

**Issue by PFery4** [tud-amr/social_vrnn#9]
In the Support file, we can see the rotate_batch_to_local_frame() function which is being invoked when passing the `--rotated_grid true` flag while training.
The function calculates the heading angle of the agent, and then applies a rotation of the user's coordinates using this heading angle.

https://github.com/tud-amr/social_vrnn/blob/707cadaac2f42cd869608cb3927ea25a4a60a1e0/src/data_utils/Support.py#L107
Upon running this specific line, the interpreter raises the following error:
```
Traceback (most recent call last):
  File "train.py", line <line where getBatch gets called>, in <module>
    batch_x, batch_vel, batch_pos, batch_goal, batch_grid, batch_ped_grid, batch_y, batch_pos_target, other_agents_pos, new_epoch = data_prep.getBatch()
  File "/path/to/DataHandlerLSTM.py", line <getBatch line>, in getBatch
    _, self.batch_y = sup.rotate_batch_to_local_frame(self.batch_y, self.batch_x)
  File "/path/to/Support.py", line <rotate_batch_to_local_frame line>, in rotate_batch_to_local_frame
    bx[batch_idx, tbp_step, 2:] = np.dot(rot_mat, bx[batch_idx, tbp_step, 2:])
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (2,2) and (34,) not aligned: 2 (dim 1) != 34 (dim 0)
```

This is due to the fact that the velocity/position array `bx` stores the coordinates in a single dimension, while the application of the rotation matrix demands that the positions and velocities be organised in a format which allows for this rotation.

Looking at the implementation of this line of code, I see that the goal is to rotate every coordinates contained within bx *except* the first two values, which correspond to the position at time of origin t_0.
We can fix this by commenting out the line of code, and iterating over the desired coordinates of the array: replace the highlighted code line with this:

```
      for pred_step in range(1, bx.shape[2] // 2):
        bx[batch_idx, tbp_step, 2 * pred_step:2 * (pred_step + 1)] = np.dot(
          rot_mat, bx[batch_idx, tbp_step, 2 * pred_step:2 * (pred_step + 1)]
        )
```

This should behave the same way as the original implementation. However I am not 100% certain whether this implementation is correct still. Rotating along the heading angle in this way essentially means that, although the velocity components will be properly transformed, the positions won't, as they are still expressed in terms of the global world coordinate system, and as such, will be rotated along this coordinate system, while they need to be rotated along the point of origin of the agent, is that correct?

I will continue my investigation of this bit of code, if I make any advancements or discoveries here, I will post them.

(Also, I will try to submit a pull request with the fix if I can, the problem is I am working on a number of elements of the repository, and I wouldn't want my additional implementations altering the state of the original repo. If there is a way for me to submit a pull request containing only specific lines / bug fixes without also submitting my unrelated / irrelevant work, that would be nice to know).

**Comment by PFery4** [comment]
![image](https://user-images.githubusercontent.com/61045673/196451560-5a6a7617-fc8e-4e57-914e-e67c80db6f57.png)

Here's a render of the position and velocity (left/right) coordinates before and after (up/down) the transformation.
From this we can see the velocity is correctly transformed, but the position is not. I have an idea how to fix this issue, will keep investigating this shortly.

**Comment by PFery4** [comment]
![image](https://user-images.githubusercontent.com/61045673/196483849-b215a3ed-c7ff-4618-9787-4932df68d488.png)

I think the desired behaviour is to apply the transformation to every component of the position (that includes also the first component). This way the trajectory itself does not become deformed. The fix is simply to remove the `1` announcing the starting argument of the `range()` in my previous snippet.

**Comment by bbrito** [comment]
@PFery4 thank you so much for you PR! I have approved it and merged it!
